"""
Mock AI service for development.

This simulates AI-generated code reviews until
the real OpenAI API is connected.
"""

from backend.core.logger import logger


class AIService:
    """Mock AI review service."""

    def review_code(self, code: str, language: str) -> str:
        logger.info("Generating mock AI review...")

        review = f"""
# AI Code Review Report

## Language
{language}

## Overall Rating
⭐⭐⭐⭐☆ (4/5)

## Strengths
- Code is syntactically correct.
- Easy to understand.
- Good readability.

## Suggestions
- Add comments where necessary.
- Use meaningful variable names.
- Add proper exception handling.
- Replace print() with logging in production.
- Consider adding unit tests.

## Security
No obvious security issues detected.

## Performance
Performance looks acceptable for this example.

## Maintainability
The code is maintainable but can be improved with better documentation.

---
This review was generated by the Mock AI Service.
"""

        return review.strip()


ai_service = AIService()