name: AI Code Review Bot

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  ai-review:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger AI Code Review
        run: |
          curl -X POST \
          "https://ai-code-review-bot-dwe8.onrender.com/api/v1/github/pulls/${{ github.event.pull_request.number }}/review"